# CI de Nível 03 - Disparo após a conclusão de um pipeline

# Nome do nosso 'Pipeline'
name: 'Execução por Deploy'

# Regras de disparo (gatilhos/triggers)
# Gatilho de execução manual = workflow_dispatch
# Gatilho de execução agendada = schedule
# Gatilho de excução a partir de outro pipeline = workflow_run

on:
    workflow_run:
        workflows: ['Execução Manual']
        types:
            - completed

# Trabalhos/tarefas dentro do pipeline = jobs
jobs:
    e2e-tests:
        # Nome do trabalho
        name: 'Execução de Testes E2E'

        # Execução em um container Docker (https://github.com/actions/runner-images)
        runs-on: ubuntu-latest

        # Passos do script de build
        steps:
            # Clone do projeto (https://github.com/marketplace/actions/checkout)
            - name: 'Clone do repositório'
              uses: actions/checkout@v4

            # Instalação do Node.js
            - name: 'Instalação do Node.js'
              uses: actions/setup-node@v4
              with:
                  node-version: '22.x'

            # Instalação do Yarn
            - name: 'Instalação do Yarn'
              run: npm install --global yarn
            
            # Instalação das dependências do projeto
            - name: 'Instalação das dependências do projeto'
              run: yarn install

            # Instalação do Playwright
            - name: 'Instalação do Playwright'
              run: yarn playwright install
              
            # Execução dos testes E2E
            - name: 'Execução dos testes E2E'
              run: yarn run e2e

            
            
